# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[main]]
  name = "Projects"
  url = "#projects"
  identifier = "projects"
  weight = 4

[[main]]
  name = "Repos"
  url = "#"
  identifier = "repos"
  weight = 4


[[main]]
  name = "RecSearch"
  url = "https://www.github.com/docmanny/smRecSearch/"
  parent = "repos"
  weight = 1

[[main]]
  name = "PromegaParser"
  url = "https://www.github.com/docmanny/PromegaParser/"
  parent = "repos"
  weight = 2

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "https://github.com/docmanny/cv/raw/master/JuanVazquezCV.pdf"
  weight = 7