# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Vazquez Lab'
    description: 'Juan Manuel Vazquez is a biologist studying the evolution of lifespan and aging across biological levels throughout the tree of life.'
    twitter: 'TheMainManManny'
    bluesky: 'themainmanmanny.bsky.social'
  analytics:
    google_analytics: 'G-5XKK7Z3YGK'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      filename: "labLogo.svg"
      text: "Juan Manuel Vazquez"

# Site footer
footer:
  copyright:
    notice: '© {year} Juan Manuel Vazquez. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: '2006-01-02'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false


extensions:
  academicons:
    enable: true

