language: ruby
rvm:
- 2.1.10
env:
  global:
    secure: ijm8e/SF4KWuB+JyXGyas1S0ym33BtSzvNye7khk62WHz7Y8FyFEuQUQwiA1JxCYK5qV4iZfYK9Pu2zK8TUaYXvlr8kq6Jzn+xCkXSyhxkqyOxcRCrsdtwg12ICavwHONa6F69Tjx0syqPPZKJjKWJ5LTfpfDfXDH5i7tayTw1A/VIPFPy8MVqyPI4HwNw8JHmRnN+p5bzBncdn5f7SWs2ibSEfaewXOf2rx0int1/FLLvSyNLi6/gnZql1TsBM50aAvBZyTOSSV0zDEPhUcNYUTcLzL0qhFn1jRrayDXYCLyM8CYizj+Tv2Pp8oU4fDneehZk9PydEL379TIA9Tzd8IQvbZkt2H9jcQsUC9bHgdRsYVWeZ1MfUbkY89+izNkgt9YvbEOLjJKoggU4EMGndiItK1/oPhl+TNtDDq7/AAruHCn4O1CtFC+aaQFmx75TZPOWiUVa5LrRtXSvNbnjNTRRnvKatf8TV0xwRZn+0U1sD4/6yIzQsTupwraqZ428tYRh6Xv3iRELUMEO3uqTYPBvEkTTITjTkI4q17hHrvtz+n3cGOIxJbGnVCh2gv+fnI4+/GFBOJebFmeiz+rdD4T0vy0XYPWUpJXqO1X66vhYtwLC9QWWkGHkgXYrudZWs/Rd57vWovGDYjXtu8Nhtoous2W9586Hx21+ABf0I=
