theme: jekyll-theme-slate

gems:
  - jekyll-seo-tag
  - jekyll-paginate
title: Juan Manuel Vazquez
description: Human Genetics Graduate Student at the University of Chicago

paginate: 5

google_analytics: UA-93059474-1
