[build]
command = 'hugo --gc --minify'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.144.2'
RUBY_VERSION = '3.4.2'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
